services:
  biller-simulator:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.kantor.deploy
    image: harbor.local/react-app/biller-simulator-json:resultv2
    container_name: biller-simulator-frontend
    ports:
      - "41923:80"
    restart: unless-stopped
    networks:
      - biller-simulator-json-net

networks:
  biller-simulator-json-net:
    external: true
    name: biller-simulator-json-net
